version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: projeto_base
      MYSQL_USER: lucas
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - data_mysql_projeto_base:/var/lib/mysql  # Mapeia um diretório local para o diretório do MySQL

volumes:
  data_mysql_projeto_base: